name: Assignment number One DevOps University Course
on: 
  push:
    branches: [ main ]
#env:
  #  docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
  #  docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Scan-with-Sonarcloud-the-code:
    name: SonarCloud scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Snyk-code-scan:
    name: Snyk can for vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        with:
          args: ${{ github.workspace }}/src
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout new repository 
      uses: actions/checkout@v3
    - name: Upload the new repository
      uses: actions/upload-artifact@v3
      with:
        name: code
        path: .

  Trivy-scan:
    needs: Clone-down
    name: Trivy scan
    runs-on: ubuntu-latest
    steps:
    - name: Download repository
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
          
    - name: Build docker image
      run: docker build -t assignmentdevops ./src
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/assignmentdevops'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

  Publish-Docker-image:
    name: Publish the docker image
    needs: Trivy-scan
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download repo
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .

      - name: Build docker image
        run: docker build -t assignmentdevops ./src

      - name: Add tag to docker image
        run: docker tag assignmentdevops ${{ secrets.DOCKERHUB_USERNAME }}/assignmentdevops
      
      - name: Publish to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/assignmentdevops